### ISSUE TITLE
Intellisense for consuming step inputs

### ISSUE THREAD

**Issue by itowlson** [deislabs/porter-vscode#10]
When a prior step has an output, that output should be available as an completion item for values in subsequent steps (`bundle.output.<stepname>.<outputname>` I think).

**Comment by carolynvs** [comment]
Steps don't have unique names, just descriptions, but outputs do have unique names per bundle. So we can do `bundle.output.outputname`.

So it would look something like this (abbreviated for clarity):

```yaml

install:
- helm:
     outputs:
     - name: output1
- exec:
     command: echo
     args:
     - "source: bundle.outputs.output1"
```
