### ISSUE TITLE
Support bundle.images.*

### ISSUE THREAD

**Issue by carolynvs** [deislabs/porter-vscode#41]
The porter.yaml file can have image maps defined and the templating supports referencing those images by name. It is currently a dictionary map (which none of the other types do, they are all lists with a `name` field). 

Is it a huge pain to add support for this type as it works right now?

```yaml
images:
  mysql:
      description: MySQL
      imageType: docker
      repository: docker.io/mysql
      tag: "5.7.28"

install:
- helm:
    description: "Install MySQL"
    name: "{{ bundle.parameters.mysql-name }}"
    set:
      image: "{{ bundle.images.mysql.repository }}"
      imageTag: "{{ bundle.images.mysql.tag }}"
```
